const portfolioObjects = [
	{
		img:"/assets/img/p-quizit2.png",
		title:"QuizIt!",
		description:"QuizIt is a live, multiplayer trivia game. QuizIt ensures that all users are seeing the same question and playing at the same time. Mobile compatible.",
		urlDemo:"https://fierce-oasis-31783.herokuapp.com/",
		urlCode:"https://github.com/Binary-Squad/QuizIt",
		details:["Bootstrap","MERN","Socket.io","Passportjs","CORS","JWT","Mongoose","Heroku","Animation","Mobile"],
	},
	{
		img:"/assets/img/p-portfolio.png",
		title:"JP&apos;s Portfolio",
		description:"This portfolio site is also a portfolio piece! It is pointlessly built with a full MERN stack. Perhaps I will add some backend functionality later. This site was built in 1 day.",
		urlDemo:"https://peaceful-inlet-20360.herokuapp.com/",
		urlCode:"https://github.com/jonmpan/new-portfolio",
		details:["Materialize","React","Nodejs","Express","Heroku","SSL","Components","Mobile","Desktop"],
	},
	{
		img:"/assets/img/p-closets.png",
		title:"Closets x3",
		description:"Closets Closets Closets is an MVC concept site where you can post items you may own. While you cannot truly login, you can still make a snazzy collection.",
		urlDemo:"https://floating-thicket-42503.herokuapp.com/",
		urlCode:"https://github.com/the-bristools/closetsclosetsclosets",
		details:["Materialize","Handlebars","Nodejs","MVC","Express","JQuery","ORM","Sequelize","Heroku"],
	},
	{
		img:"/assets/img/p-capi.png",
		title:"cAPI-PASTE",
		description:"cAPI-PASTE was my first project. Made entirely with static HTML, this site demonstrates some common use cases for some API&apos;s.",
		urlDemo:"https://first-project-tom-jon-suneetha.github.io/cAPI-PASTE/",
		urlCode:"https://github.com/First-Project-Tom-Jon-Suneetha/cAPI-PASTE",
		details:["Bootstrap","AceText","Jquery","AJAX","GoogleAPI","JQuery","Giphy","YoutubeAPI","Github Pages","Animation"],
	},
	{
		img:"/assets/img/p-omnom.png",
		title:"OmnomBurger",
		description:"This site is built with an MVC structure and utilized MySQL and Sequelize for data management. It also has your standard RESTful API.",
		urlDemo:"https://fast-retreat-55192.herokuapp.com/",
		urlCode:"https://github.com/jonmpan/Omnom-Dat-Burger-Sequelize",
		details:["Materialize","Sequelize","Nodejs","JQuery","ORM","REST","Express","MVC","Animation"],
	},
	{
		img:"/assets/img/p-ajax.png",
		title:"Giphy Ajax",
		description:"WARNING! HAS SOUND! This site is a single html file that does API calls to Giphy and renders them. It also has infinite loading/scrolling and sound effects.",
		urlDemo:"https://jonmpan.github.io/ajax-assignment/",
		urlCode:"https://github.com/jonmpan/ajax-assignment/",
		details:["JQuery","Ajax","GiphyAPI","CORS","JQuery","JWT","Animation","Video","Audio"],
	},
	{
		img:"/assets/img/p-cirno-clicker.png",
		title:"Cirno Clicker",
		description:"WARNING! HAS SOUND! A pointless clicker game that utilizes firebase. Ideally I would convert this to cultivate multi-player lobbies on its own but alas, I never got to that.",
		urlDemo:"https://jonmpan.github.io/firebase-assignment/player1",
		urlCode:"https://github.com/jonmpan/firebase-assignment",
		details:["Cirno","Game","Firebase","JQuery","Javascript","Audio","Animation"],
	},
	{
		img:"/assets/img/p-cirno-trivia.png",
		title:"Cirno Math",
		description:"WARNING! HAS SOUND! A stupidly difficult math game. The joke is that Cirno thinks she&apos;s smart but in reality, she&apos;s really stupid.",
		urlDemo:"https://jonmpan.github.io/trivia-game/",
		urlCode:"https://github.com/jonmpan/trivia-game",
		details:["Cirno","Game","Math","Jquery","Video","Audio"],
	},
	{
		img:"/assets/img/p-cirno-hangman.png",
		title:"Cirno Hangman",
		description:"WARNING! HAS SOUND! The first Javascript I ever wrote. Riddled with inefficient code. Looking back on this brings nostalgia to me.",
		urlDemo:"https://jonmpan.github.io/hangman-game/",
		urlCode:"https://github.com/jonmpan/hangman-game",
		details:["Cirno","Game","JQuery","Animation","Audio"],
	}
]

module.exports = portfolioObjects;